import type { ExerciseDefinition } from '@/types/exercise'

export const exercises: ExerciseDefinition[] = [
  {
    slug: 'homelab-infrastructure',
    title: 'Homelab Infrastructure',
    description: 'Model a home server cluster with SysML. Define the package architecture, hardware blocks, socket allocation constraints, and network traffic routing.',
    domain: 'IT Infrastructure',
    difficulty: 'beginner',
    isFree: true,
    stages: [
      {
        index: 0,
        title: 'Package Architecture',
        diagramType: 'pkg',
        taskPrompt: 'Build a Package Diagram with these 5 packages:',
        requiredElements: [
          '📦 Package: Requirements',
          '📦 Package: Structure',
          '📦 Package: Behavior',
          '📦 Package: Homelab Cluster Context',
          '📦 Package: Component Library',
        ],
        instructions: 'Create a Package Diagram for the Homelab Cluster context. You need packages for: Requirements, Structure, Behavior, Homelab Cluster Context, and Component Library. Use the Package tool to place all five packages on the canvas.',
        hints: [
          'Each major concern gets its own package in SysML.',
          'The "Homelab Cluster Context" package is the root system context.',
          'Component Library holds reusable block definitions.',
        ],
      },
      {
        index: 1,
        title: 'Block Definition',
        diagramType: 'bdd',
        inputMode: 'kerml',
        taskPrompt: 'Build a BDD with these blocks and relationships:',
        requiredElements: [
          '⬛ Block: Homelab Server',
          '⬛ Block: AOOSTAR Gem 12',
          '⬛ Block: RTX 4090',
          '⬛ Block: TP-Link Switch',
          '♦ Composition (*--) from Server to each component',
        ],
        instructions: 'Create a Block Definition Diagram (BDD) showing the Homelab Server system. The server is composed of: AOOSTAR Gem 12 (mini PC), RTX 4090 (GPU), and TP-Link Switch (network). Use Composition (*--) relationships to show containment.',
        hints: [
          'Composition means the child cannot exist without the parent.',
          'Use the Composition connector from the toolbar.',
          'All hardware components are "parts" of the Homelab Server block.',
        ],
      },
      {
        index: 2,
        title: 'Internal Block Diagram',
        diagramType: 'ibd',
        taskPrompt: 'Build an IBD with these ports and allocations:',
        requiredElements: [
          '◈ Port: Socket 1',
          '◈ Port: Socket 2',
          '↗ Allocation (<<allocate>>) to each socket',
          '⚠ Do NOT add Socket 3 or Socket 4',
        ],
        instructions: 'Create an Internal Block Diagram (IBD) showing the CPU socket allocation. Add Socket 1 and Socket 2 as Ports. Use Allocation (<<allocate>>) to assign components. Constraint: Socket 3 and Socket 4 must NOT appear — they are reserved for future expansion.',
        hints: [
          'Ports represent interfaces or physical connections in SysML.',
          'Allocation shows which component occupies which resource.',
          'Anti-pattern: Never expose reserved sockets in the active IBD.',
        ],
      },
      {
        index: 3,
        title: 'Traffic Routing Activity',
        diagramType: 'act',
        taskPrompt: 'Build an Activity Diagram with this flow:',
        requiredElements: [
          '▷ Action: Internet',
          '▷ Action: TP-Link Switch',
          '▷ Action: AOOSTAR',
          '— Association control flows between each action',
        ],
        instructions: 'Create an Activity Diagram showing network traffic routing. The flow should be: Internet → TP-Link Switch → AOOSTAR. Add Action nodes for each step and connect them with control flows.',
        hints: [
          'Actions represent executable steps in the system.',
          'Control flow arrows show the sequence of execution.',
          'Label your actions clearly — they describe what happens at each stage.',
        ],
      },
    ],
  },

  {
    slug: 'deep-space-network',
    title: 'Deep Space Network',
    description: 'Model a spacecraft communication architecture. Define ground and space segments, the orbiter block hierarchy, transceiver wiring, and the telemetry downlink activity flow.',
    domain: 'Aerospace',
    difficulty: 'intermediate',
    isFree: true,
    stages: [
      {
        index: 0,
        title: 'Communication Architecture',
        diagramType: 'pkg',
        taskPrompt: 'Build a Package Diagram with these 4 packages:',
        requiredElements: [
          '📦 Package: Ground Segment',
          '📦 Package: Space Segment',
          '📦 Package: Requirements',
          '📦 Package: Behavior',
        ],
        instructions: 'Create a Package Diagram for the spacecraft communication system. Include packages for: Ground Segment, Space Segment, Requirements, and Behavior.',
        hints: [
          'Ground Segment and Space Segment are the two main operational contexts.',
          'Separating Requirements and Behavior into packages is standard MBSE practice.',
        ],
      },
      {
        index: 1,
        title: 'Space Segment Blocks',
        diagramType: 'bdd',
        taskPrompt: 'Build a BDD for the Space Segment:',
        requiredElements: [
          '⬛ Block: Orbiter',
          '⬛ Block: Telemetry System',
          '⬛ Block: Transceiver',
          '⬛ Block: Antenna Array',
          '♦ Composition (*--) from Orbiter to each subsystem',
        ],
        instructions: 'Create a BDD for the Space Segment. The Orbiter block is composed of: Telemetry System, Transceiver, and Antenna Array. Use Composition (*--) relationships.',
        hints: [
          'The Orbiter is the top-level block for the space segment.',
          'Each subsystem (Telemetry, Transceiver, Antenna) is a composed part.',
        ],
      },
      {
        index: 2,
        title: 'Transceiver Wiring',
        diagramType: 'ibd',
        taskPrompt: 'Build an IBD for the Transceiver:',
        requiredElements: [
          '◈ Port: RF In',
          '◈ Port: RF Out',
          '⬛ Block: Amplifier',
          '⬛ Block: Modem',
          '↗ Allocation: Amplifier → RF In, Modem → RF Out',
          '⚠ Do NOT add USB interfaces',
        ],
        instructions: 'Create an IBD for the Transceiver. Add ports: RF In and RF Out. Use Allocation to assign: Amplifier to RF In, Modem to RF Out. Constraint: USB interfaces must NOT appear in the RF signal path.',
        hints: [
          'RF ports represent the radio frequency interface boundaries.',
          'The Amplifier conditions the incoming signal; the Modem processes outgoing data.',
          'USB is a digital interface and has no place in the RF signal path.',
        ],
      },
      {
        index: 3,
        title: 'Downlink Data Flow',
        diagramType: 'act',
        taskPrompt: 'Build an Activity Diagram for the downlink sequence:',
        requiredElements: [
          '▷ Action: Collect Data',
          '▷ Action: Modulate Signal',
          '▷ Action: Transmit to Ground',
          '— Control flows connecting each action in sequence',
        ],
        instructions: 'Create an Activity Diagram for the telemetry downlink sequence: Collect Data → Modulate Signal → Transmit to Ground. Connect with control flow arrows.',
        hints: [
          'This activity runs aboard the spacecraft during a downlink pass.',
          'Each action maps to a subsystem: Telemetry collects, Transceiver modulates and transmits.',
        ],
      },
    ],
  },

  {
    slug: 'av-perception',
    title: 'Autonomous Vehicle Perception',
    description: 'Model the perception subsystem of an autonomous vehicle. Define sensing and processing packages, sensor block composition, CAN/Ethernet bus allocation, and the object detection pipeline.',
    domain: 'Automotive',
    difficulty: 'intermediate',
    isFree: false,
    stages: [
      {
        index: 0,
        title: 'AV System Architecture',
        diagramType: 'pkg',
        taskPrompt: 'Build a Package Diagram with these 5 packages:',
        requiredElements: [
          '📦 Package: Sensing',
          '📦 Package: Processing',
          '📦 Package: Actuation',
          '📦 Package: Safety',
          '📦 Package: Requirements',
        ],
        instructions: 'Create a Package Diagram for the AV system. Include packages for: Sensing, Processing, Actuation, Safety, and Requirements.',
        hints: [
          'Safety is an explicit package — AV systems must trace all safety requirements.',
          'Sensing, Processing, and Actuation are the three operational domains.',
        ],
      },
      {
        index: 1,
        title: 'Sensor Block Hierarchy',
        diagramType: 'bdd',
        taskPrompt: 'Build a BDD for the AV Platform:',
        requiredElements: [
          '⬛ Block: AV Platform',
          '⬛ Block: LiDAR Unit',
          '⬛ Block: Camera Array',
          '⬛ Block: Radar Module',
          '⬛ Block: ECU',
          '♦ Composition (*--) from AV Platform to each sensor',
        ],
        instructions: 'Create a BDD for the AV Platform. Compose it from: LiDAR Unit, Camera Array, Radar Module, and ECU (Electronic Control Unit). Use Composition.',
        hints: [
          'The ECU is the central processing block that receives all sensor data.',
          'LiDAR, Camera, and Radar are the three primary sensing modalities.',
        ],
      },
      {
        index: 2,
        title: 'Sensor Bus Allocation',
        diagramType: 'ibd',
        taskPrompt: 'Build an IBD for sensor bus interfaces:',
        requiredElements: [
          '◈ Port: CAN Bus',
          '◈ Port: Ethernet',
          '↗ Allocation: LiDAR → Ethernet',
          '↗ Allocation: Radar → CAN Bus',
          '⚠ Do NOT add WiFi or wireless interfaces',
        ],
        instructions: 'Create an IBD showing bus allocation. Add ports: CAN Bus and Ethernet. Allocate: LiDAR to Ethernet (high bandwidth), Radar to CAN Bus (low latency). Constraint: WiFi/wireless must NOT appear in the safety-critical sensor path.',
        hints: [
          'LiDAR generates point cloud data requiring high bandwidth — Ethernet is correct.',
          'Radar uses CAN Bus for its deterministic low-latency communication.',
          'Wireless interfaces introduce unacceptable latency variance in safety systems.',
        ],
      },
      {
        index: 3,
        title: 'Perception Pipeline',
        diagramType: 'act',
        taskPrompt: 'Build an Activity Diagram for the perception pipeline:',
        requiredElements: [
          '▷ Action: Capture Sensor Data',
          '▷ Action: Fuse Point Clouds',
          '▷ Action: Classify Objects',
          '▷ Action: Send to Planner',
          '— Control flows in sequence',
        ],
        instructions: 'Create an Activity Diagram for the perception pipeline: Capture Sensor Data → Fuse Point Clouds → Classify Objects → Send to Planner.',
        hints: [
          'Sensor fusion (combining LiDAR + Radar data) is the critical second step.',
          'The Planner is the downstream planning module that receives classified object data.',
        ],
      },
    ],
  },

  {
    slug: 'infusion-pump',
    title: 'Medical Infusion Pump',
    description: 'Model a safety-critical infusion pump system. Define fluid delivery and safety packages, pump hardware composition, control interface allocation, and the drug delivery cycle activity.',
    domain: 'Medical / Safety-Critical',
    difficulty: 'intermediate',
    isFree: false,
    stages: [
      {
        index: 0,
        title: 'System Package Architecture',
        diagramType: 'pkg',
        taskPrompt: 'Build a Package Diagram with these 5 packages:',
        requiredElements: [
          '📦 Package: Safety',
          '📦 Package: Fluid Delivery',
          '📦 Package: Alarming',
          '📦 Package: Software',
          '📦 Package: Requirements',
        ],
        instructions: 'Create a Package Diagram for the Infusion Pump system. Include packages for: Safety, Fluid Delivery, Alarming, Software, and Requirements.',
        hints: [
          'Safety requirements must be explicitly separated for FDA/IEC 62304 traceability.',
          'Alarming is a first-class package — alert failures are a primary failure mode.',
        ],
      },
      {
        index: 1,
        title: 'Pump Hardware Blocks',
        diagramType: 'bdd',
        taskPrompt: 'Build a BDD for the Infusion Pump System:',
        requiredElements: [
          '⬛ Block: Infusion Pump',
          '⬛ Block: Pump Motor',
          '⬛ Block: Flow Sensor',
          '⬛ Block: Alarm Module',
          '⬛ Block: Display Unit',
          '♦ Composition (*--) from Infusion Pump to each component',
        ],
        instructions: 'Create a BDD for the Infusion Pump System. Compose it from: Pump Motor, Flow Sensor, Alarm Module, and Display Unit. Use Composition.',
        hints: [
          'The Flow Sensor provides closed-loop feedback to the motor controller.',
          'The Display Unit is the human-machine interface (HMI) for clinicians.',
        ],
      },
      {
        index: 2,
        title: 'Control Interface Allocation',
        diagramType: 'ibd',
        taskPrompt: 'Build an IBD for the control interface:',
        requiredElements: [
          '◈ Port: Control Signal In',
          '◈ Port: Feedback Out',
          '↗ Allocation: Pump Motor → Control Signal In',
          '↗ Allocation: Flow Sensor → Feedback Out',
          '⚠ Do NOT add wireless, Bluetooth, or WiFi',
        ],
        instructions: 'Create an IBD showing the control interface. Add ports: Control Signal In and Feedback Out. Allocate: Pump Motor to Control Signal In, Flow Sensor to Feedback Out. Constraint: Wireless, Bluetooth, and WiFi interfaces must NOT appear in the drug delivery path.',
        hints: [
          'The motor receives commands via Control Signal In.',
          'The Flow Sensor returns measured flow rate via Feedback Out — closing the control loop.',
          'Wireless in drug delivery paths violates IEC 60601 electromagnetic interference requirements.',
        ],
      },
      {
        index: 3,
        title: 'Delivery Cycle Activity',
        diagramType: 'act',
        taskPrompt: 'Build an Activity Diagram for the delivery cycle:',
        requiredElements: [
          '▷ Action: Check Flow Rate',
          '▷ Action: Compare to Prescription',
          '▷ Action: Adjust Motor Speed',
          '▷ Action: Log Event',
          '— Control flows in sequence',
        ],
        instructions: 'Create an Activity Diagram for the delivery cycle: Check Flow Rate → Compare to Prescription → Adjust Motor Speed → Log Event.',
        hints: [
          'This is a continuous control loop that runs every 100ms during active infusion.',
          'Logging every event is required for FDA adverse event reporting.',
        ],
      },
    ],
  },

  {
    slug: 'satellite-power',
    title: 'Satellite Power Subsystem',
    description: 'Model the electrical power subsystem of a satellite. Define power generation and storage packages, the power control block hierarchy, DC bus allocation, and the power management activity.',
    domain: 'Aerospace / Electrical',
    difficulty: 'advanced',
    isFree: false,
    stages: [
      {
        index: 0,
        title: 'Power System Architecture',
        diagramType: 'pkg',
        taskPrompt: 'Build a Package Diagram with these 5 packages:',
        requiredElements: [
          '📦 Package: Power Generation',
          '📦 Package: Storage',
          '📦 Package: Distribution',
          '📦 Package: Thermal',
          '📦 Package: Requirements',
        ],
        instructions: 'Create a Package Diagram for the satellite power subsystem. Include packages for: Power Generation, Storage, Distribution, Thermal, and Requirements.',
        hints: [
          'Thermal management is always a separate package — power dissipation drives thermal design.',
          'Distribution covers the power bus and all downstream loads.',
        ],
      },
      {
        index: 1,
        title: 'Power Block Hierarchy',
        diagramType: 'bdd',
        taskPrompt: 'Build a BDD for the Power Subsystem:',
        requiredElements: [
          '⬛ Block: Solar Array',
          '⬛ Block: Battery Bank',
          '⬛ Block: Power Control Unit',
          '⬛ Block: Bus Regulator',
          '♦ Composition (*--) connecting all components',
        ],
        instructions: 'Create a BDD for the Power Subsystem. Compose it from: Solar Array, Battery Bank, Power Control Unit (PCU), and Bus Regulator. Use Composition.',
        hints: [
          'The PCU is the central block managing charge and discharge cycles.',
          'The Bus Regulator maintains constant 28V output to downstream loads.',
        ],
      },
      {
        index: 2,
        title: 'DC Bus Allocation',
        diagramType: 'ibd',
        taskPrompt: 'Build an IBD for the power distribution bus:',
        requiredElements: [
          '◈ Port: 28V Bus Out',
          '◈ Port: Charge Port',
          '↗ Allocation: Solar Array → Charge Port',
          '↗ Allocation: Bus Regulator → 28V Bus Out',
          '⚠ Do NOT add AC power, 120V, or 240V',
        ],
        instructions: 'Create an IBD for the power distribution. Add ports: 28V Bus Out and Charge Port. Allocate: Solar Array to Charge Port, Bus Regulator to 28V Bus Out. Constraint: AC power (120V, 240V) must NOT appear — this is a DC-only spacecraft bus.',
        hints: [
          'Spacecraft power buses are always DC — AC would require inverters adding mass and failure modes.',
          'The 28V standard is the ECSS spacecraft bus voltage specification.',
        ],
      },
      {
        index: 3,
        title: 'Power Management Activity',
        diagramType: 'act',
        taskPrompt: 'Build an Activity Diagram for power management:',
        requiredElements: [
          '▷ Action: Collect Solar Energy',
          '▷ Action: Regulate Voltage',
          '▷ Action: Distribute to Loads',
          '▷ Action: Monitor State of Charge',
          '— Control flows in sequence',
        ],
        instructions: 'Create an Activity Diagram for power management: Collect Solar Energy → Regulate Voltage → Distribute to Loads → Monitor State of Charge.',
        hints: [
          'State of Charge monitoring feeds back to the charge controller to prevent overcharge.',
          'This cycle runs continuously during the sunlit portion of each orbit.',
        ],
      },
    ],
  },

  {
    slug: 'railway-signaling',
    title: 'Railway Signaling System',
    description: 'Model a safety-critical railway interlocking system. Define interlocking and signaling packages, the route controller block hierarchy, signal command interfaces, and the route setting activity.',
    domain: 'Transportation / Safety-Critical',
    difficulty: 'advanced',
    isFree: false,
    stages: [
      {
        index: 0,
        title: 'Signaling Architecture',
        diagramType: 'pkg',
        taskPrompt: 'Build a Package Diagram with these 5 packages:',
        requiredElements: [
          '📦 Package: Interlocking',
          '📦 Package: Track Circuit',
          '📦 Package: Signaling',
          '📦 Package: Communication',
          '📦 Package: Requirements',
        ],
        instructions: 'Create a Package Diagram for the railway signaling system. Include packages for: Interlocking, Track Circuit, Signaling, Communication, and Requirements.',
        hints: [
          'Interlocking is the safety-critical logic that prevents conflicting route authorizations.',
          'Track Circuit and Signaling are the field equipment packages.',
        ],
      },
      {
        index: 1,
        title: 'Interlocking Block Hierarchy',
        diagramType: 'bdd',
        taskPrompt: 'Build a BDD for the Interlocking System:',
        requiredElements: [
          '⬛ Block: Interlocking System',
          '⬛ Block: Route Controller',
          '⬛ Block: Signal Head',
          '⬛ Block: Point Machine',
          '⬛ Block: Track Detector',
          '♦ Composition (*--) from Interlocking System to each component',
        ],
        instructions: 'Create a BDD for the Interlocking System. Compose it from: Route Controller, Signal Head, Point Machine, and Track Detector. Use Composition.',
        hints: [
          'The Route Controller is the logic unit — it authorizes routes based on track occupancy.',
          'Point Machine physically moves rail switches; Signal Head displays aspects to drivers.',
        ],
      },
      {
        index: 2,
        title: 'Signal Interface Allocation',
        diagramType: 'ibd',
        taskPrompt: 'Build an IBD for the interlocking interfaces:',
        requiredElements: [
          '◈ Port: Command Port',
          '◈ Port: Status Port',
          '↗ Allocation: Signal Head → Command Port',
          '↗ Allocation: Track Detector → Status Port',
          '⚠ Do NOT add wireless control or WiFi control',
        ],
        instructions: 'Create an IBD for the interlocking interfaces. Add ports: Command Port and Status Port. Allocate: Signal Head to Command Port, Track Detector to Status Port. Constraint: "wireless control" and "wifi control" must NOT appear.',
        hints: [
          'Commands flow OUT to field equipment; status flows IN from track circuits.',
          'EN 50129 (Railway safety standard) prohibits wireless control of safety functions.',
        ],
      },
      {
        index: 3,
        title: 'Route Setting Activity',
        diagramType: 'act',
        taskPrompt: 'Build an Activity Diagram for the route setting sequence:',
        requiredElements: [
          '▷ Action: Request Route',
          '▷ Action: Check Track Clear',
          '▷ Action: Set Points',
          '▷ Action: Clear Signal',
          '▷ Action: Confirm Route',
          '— Control flows in sequence',
        ],
        instructions: 'Create an Activity Diagram for the route setting sequence: Request Route → Check Track Clear → Set Points → Clear Signal → Confirm Route.',
        hints: [
          'All five steps must complete before a train is authorized to proceed.',
          '"Check Track Clear" queries the Track Detector; "Set Points" commands the Point Machine.',
        ],
      },
    ],
  },
]

export function getExercise(slug: string): ExerciseDefinition | undefined {
  return exercises.find((e) => e.slug === slug)
}
